ALTER TABLE entities ADD COLUMN skipped INTEGER NOT NULL DEFAULT 0 CHECK(skipped IN (0,1));
ALTER TABLE entities ADD COLUMN skipReason TEXT NOT NULL DEFAULT '';
ALTER TABLE telegram_events ADD COLUMN skipped INTEGER NOT NULL DEFAULT 0 CHECK(skipped IN (0,1));
ALTER TABLE telegram_events ADD COLUMN skipReason TEXT NOT NULL DEFAULT '';
